
const GITHUB_AUTH_TOKEN = "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"
const GITHUB_USERNAME = "IsuruLK-007"
const SESSION_ID = "𝙰𝚂𝙸𝚃𝙷𝙰-𝙼𝙳=njgRWTJQ#e0dmJNRwYRATDke_tFtQzSQfV2vL9_rKfHy1UJVab70"


module.exports = {
GITHUB_AUTH_TOKEN,
GITHUB_USERNAME,
SESSION_ID
}
